//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.10

pub mod prelude;

pub mod api_message;
pub mod api_message_doc;
pub mod api_message_script_list;
pub mod api_message_test_record;
pub mod api_server;
